### ISSUE TITLE
Documentation imprecision

### ISSUE THREAD

**Issue by Poshi** [NKI-GCF/rumidup#5]
In the documentation, you say that the unsorted input file need to be processed thru `samtools fixmate`. But that won't always work.
If you feed a truly unsorted file to `samtools fixmate`, it will fail or give wrong results. As stated in the `samtools fixmate` manual page, you need "a name-sorted or name-collated alignment".
I see your point, you talk about the data as it arrives just after alignment, prior to sorting (hence, unsorted), but if someone want to run the program on an existing dataset, probably already sorted by coordinates, it will feed the file as is, because you say it can be unsorted, so they won't sort the file again.

**Comment by veldsla** [comment]
You are correct. I updated to the docs and refer to the aligner output as name-collated.
Thanks
